DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  lastname VARCHAR(16) NOT NULL DEFAULT '',
  firstname VARCHAR(256) NOT NULL DEFAULT '',
  nickname VARCHAR(256) NOT NULL DEFAULT '', -- login
  city VARCHAR(256) NOT NULL DEFAULT '',
  admin VARCHAR (4) DEFAULT 'NON',
  password VARCHAR(256) NOT NULL DEFAULT '', -- crypté
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

